name: My Action
description: Action Sample
inputs:
  value1:
    description: TEST
    required: true
    default: VALUE1

runs:
  using: "composite"
  steps:
    - name: Run a one-line script
      run: echo ${{ inputs.value1 }}
      shell: bash
