# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      value1:
        description: 'value1'
        required: false
        default: 'T-AUTO'
  push:
    branches: ['main']       

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: macos-latest
    env:
      global1: GLOBAL
      has-value1: ${{ github.event.inputs.value1 == 'true' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: test-expression
        env:
          TAG_NAME: v${{ github.event.inputs.value1 }}
          
        run: |
          echo ${{ github.event.inputs.value1 }}
          echo ${{ github.event.inputs.value1 || 'DMMY' }}
          echo ${{ github.event.inputs.value1 && env.TAG_NAME }}
          echo ${{ (github.event.inputs.value1 && env.TAG_NAME) || 'DMMY' }}
          echo ${{ 'Release $TAG_NAME' }}
          echo ${{ github.event.inputs.value1 && 'Release $TAG_NAME' }}
          echo ${{ github.event.inputs.value1 && format('Release {0}', env.TAG_NAME) }}
          echo ${{ github.event.inputs.value1 && format('Release {0} {1}', env.global1, env.TAG_NAME) }}
          echo ${{ (env.has-value1 && format('HAD {0}', env.has-value1)) || format('NO {0}', env.has-value1) }}
          
  test-action:
    runs-on: macos-latest
    env:
      global2: GLOBAL    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
      - name: test
        env:
          TAG_NAME: v${{ github.event.inputs.value1 }}
        uses: ./.github/actions/myaction
        with:
          value1: $TAG_NAME
      - name: test2
        env:
          TAG_NAME: v${{ github.event.inputs.value1 }}
        uses: ./.github/actions/myaction
        with:
          value1: ${{ 'Release $TAG_NAME' }} 
      - name: test3
        env:
          TAG_NAME: v${{ github.event.inputs.value1 }}
        uses: ./.github/actions/myaction
        with:
          value1: ${{ format('Release {0} {1}', env.TAG_NAME, env.global2) }} 
          
          
          
